#include "standard_error_handling.h"

void catch_non_std_exception(int err_num)
{
	std::cout << "An error occurred during the execution: unknown error";
}